on:
  # Test on PRs for any branch
  pull_request:
    branches:
      - '*'
  # Test only pushes to master branch
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Midnight of each sunday

# We don't need to run older workflows for the same PR's, since we always want the output of the newest ones.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Tests

permissions:
  contents: read

jobs:
  tests:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install toolchain
        env: 
          TARGET_TOOLCHAIN: ${{ matrix.rust }}
        run: rustup toolchain install "${TARGET_TOOLCHAIN}"
        shell: bash

      - name: Run cargo test
        env:
          API_KEY: 00000000000000000000000000000000
        with:
          command: test
          args: --features ci_test